name: Window icon not working
description: A window icon of a specific application isn't working
title: "Window icon not working for "
labels: [ "icon" ]
body:
  - id: application
    type: input
    attributes:
      label: Application that has no window icon
      placeholder: Chromium
    validations:
      required: true
  - id: app-id
    type: input
    attributes:
      label: AppID as exposed by the application
      placeholder: chromium
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        There are multiple ways to figure out the AppID of the application as seen by labwc:
        - In the labwc window switcher with a field definition of `identifier`
        - In the labwc debug log output (`labwc -d 2>/tmp/labwc.log` and `grep 'identifier=' /tmp/labwc.log`)
        - Via external tool like `wlrctl window list` (first column)
        - Via external tool like `lswt`
  - id: desktop-file-name
    type: input
    attributes:
      label: Name of the .desktop file
      description: "The .desktop file name of the application, usually located at /usr/share/applications/"
      placeholder: chromium.desktop
    validations:
      required: true
  - id: desktop-file
    type: textarea
    attributes:
      label: ".desktop file"
      description: "The .desktop file itself"
      render: desktop
    validations:
      required: true
