name: CI_void
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-linux:latest-thin-x86_64-musl
    steps:
      - name: install dependencies
        run: |
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -yu
          # Based on
          # https://github.com/void-linux/void-packages/blob/master/srcpkgs/wlroots/template
          xbps-install -y git meson gcc clang pkg-config wlroots \
            wayland-devel glslang libgbm-devel libglvnd-devel libseat-devel \
            eudev-libudev-devel libdrm-devel libinput-devel libxkbcommon-devel \
            pixman-devel wayland-devel wayland-protocols xcb-util-errors-devel \
            xcb-util-wm-devel xcb-util-renderutil-devel libxcb-devel \
            xcb-util-cursor-devel xcb-util-devel xcb-util-image-devel \
            xcb-util-keysyms-devel xcb-util-xrm-devel xorg-server-xwayland
      - uses: actions/checkout@v1
      - name: build with gcc
        run: |
          export CC=gcc
          meson build-gcc/ --werror
          ninja -C build-gcc/
      - name: build with clang
        run: |
          export CC=clang
          meson build-clang/ --werror
          ninja -C build-clang/

