name: CI_void
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/void-linux/void-linux:latest-full-x86_64-musl
    steps:
      - name: install dependencies
        run: |
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -yu
          # Just install wlroots to get all the required deps installed as well
          xbps-install -y git meson gcc pkgconf wlroots
      - uses: actions/checkout@v1
      - name: build with gcc
        run: |
          export CC=gcc
          meson build-gcc/ --werror
          ninja -C build-gcc/
      - name: build with clang
        run: |
          export CC=clang
          meson build-clang/ --werror
          ninja -C build-clang/

